title: Minterger Status
buildFuture: true
defaultContentLanguage: en
languageCode: es
baseURL: https://status.minterger.xyz
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Pi-hole
      description: The DNS server for the home network.
      category: Home Server
      link: https://pihole.minterger.xyz/
    - name: Portainer
      description: The container management system.
      category: Home Server
      link: https://portainer.minterger.xyz/
    - name: Speedtest Tacker
      description: The speedtest tracker for the home network.
      category: Home Server
      link: https://speed.minterger.xyz/
    - name: WireGuard dashboard
      description: The WireGuard dashboard for the home network.
      category: Home Server
      link: https://wg.minterger.xyz/
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: false
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Home Server
      description: The server located at home.
      closed: true
    - name: Uncategorized
      untitled: true
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
